version: '3.7'
services:
  nginx:
    container_name: barracks_nginx
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  backend:
    container_name: barracks_backend
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - "4000:4000"
    command: >
      sh -c " cd barracks &&
          python manage.py migrate &&
          python manage.py init_db &&
          python manage.py collectstatic --no-input &&
          gunicorn barracks.wsgi:application --bind 0.0.0.0:4000"
    volumes:
     - ./backend:/app
     - static_volume:/app/static
    depends_on:
     - db
  frontend:
    container_name: barracks_frontend
    restart: on-failure
    build: ./frontend
    restart: always
    env_file: .env
    volumes:
      - ./frontend:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "yarn build && serve -s build"
  db:
    container_name: barracks_db
    image: postgres:14.0-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data: